-- Hand-authored highlight map. Input: a palette variant table from palette.lua.
return function(p)
  return {
    -- Editor UI
    Normal       = { fg = p.fg, bg = p.bg },
    NormalFloat  = { fg = p.fg, bg = p.bg_alt },
    FloatBorder  = { fg = p.muted, bg = p.bg_alt },
    Cursor       = { fg = p.bg, bg = p.green },
    CursorLine   = { bg = p.bg_alt },
    CursorLineNr = { fg = p.yellow, bold = true },
    LineNr       = { fg = p.muted },
    SignColumn   = { bg = p.bg },
    ColorColumn  = { bg = p.bg_alt },
    Visual       = { bg = p.sel },
    Search       = { fg = p.bg, bg = p.yellow },
    IncSearch    = { fg = p.bg, bg = p.orange },
    MatchParen   = { fg = p.cyan, bold = true },
    Pmenu        = { fg = p.fg, bg = p.bg_alt },
    PmenuSel     = { fg = p.bg, bg = p.blue, bold = true },
    PmenuSbar    = { bg = p.surface },
    PmenuThumb   = { bg = p.muted },
    StatusLine   = { fg = p.fg, bg = p.surface },
    StatusLineNC = { fg = p.muted, bg = p.bg_alt },
    TabLine      = { fg = p.muted, bg = p.bg_alt },
    TabLineSel   = { fg = p.bg, bg = p.blue, bold = true },
    WinSeparator = { fg = p.surface },
    Folded       = { fg = p.muted, bg = p.bg_alt },
    NonText      = { fg = p.surface },
    Whitespace   = { fg = p.surface },
    Directory    = { fg = p.blue },
    Title        = { fg = p.green, bold = true },
    ErrorMsg     = { fg = p.red },
    WarningMsg   = { fg = p.orange },

    -- Legacy syntax
    Comment      = { fg = p.muted, italic = true },
    Constant     = { fg = p.orange },
    String       = { fg = p.green },
    Character    = { fg = p.green },
    Number       = { fg = p.orange },
    Boolean      = { fg = p.orange },
    Identifier   = { fg = p.fg },
    Function     = { fg = p.blue },
    Statement    = { fg = p.magenta },
    Keyword      = { fg = p.magenta },
    Conditional  = { fg = p.magenta },
    Repeat       = { fg = p.magenta },
    Operator     = { fg = p.cyan },
    PreProc      = { fg = p.cyan },
    Type         = { fg = p.yellow },
    StorageClass = { fg = p.yellow },
    Special      = { fg = p.cyan },
    Underlined   = { fg = p.blue, underline = true },
    Todo         = { fg = p.bg, bg = p.yellow, bold = true },
    Error        = { fg = p.red },

    -- Treesitter captures
    ["@variable"]          = { fg = p.fg },
    ["@variable.builtin"]  = { fg = p.red },
    ["@variable.member"]   = { fg = p.fg },
    ["@property"]          = { fg = p.fg },
    ["@parameter"]         = { fg = p.fg, italic = true },
    ["@function"]          = { fg = p.blue },
    ["@function.builtin"]  = { fg = p.cyan },
    ["@function.call"]     = { fg = p.blue },
    ["@constructor"]       = { fg = p.yellow },
    ["@keyword"]           = { fg = p.magenta },
    ["@keyword.function"]  = { fg = p.magenta },
    ["@keyword.return"]    = { fg = p.magenta },
    ["@conditional"]       = { fg = p.magenta },
    ["@string"]            = { fg = p.green },
    ["@string.escape"]     = { fg = p.cyan },
    ["@number"]            = { fg = p.orange },
    ["@boolean"]           = { fg = p.orange },
    ["@type"]              = { fg = p.yellow },
    ["@type.builtin"]      = { fg = p.yellow, italic = true },
    ["@comment"]           = { fg = p.muted, italic = true },
    ["@punctuation"]       = { fg = p.fg_dim },
    ["@punctuation.bracket"] = { fg = p.fg_dim },
    ["@tag"]               = { fg = p.red },
    ["@tag.attribute"]     = { fg = p.yellow },
    ["@constant"]          = { fg = p.orange },
    ["@constant.builtin"]  = { fg = p.orange },

    -- LSP / diagnostics
    DiagnosticError = { fg = p.red },
    DiagnosticWarn  = { fg = p.orange },
    DiagnosticInfo  = { fg = p.blue },
    DiagnosticHint  = { fg = p.cyan },
    DiagnosticUnderlineError = { undercurl = true, sp = p.red },
    DiagnosticUnderlineWarn  = { undercurl = true, sp = p.orange },
    DiagnosticUnderlineInfo  = { undercurl = true, sp = p.blue },
    DiagnosticUnderlineHint  = { undercurl = true, sp = p.cyan },
    LspReferenceText  = { bg = p.sel },
    LspReferenceRead  = { bg = p.sel },
    LspReferenceWrite = { bg = p.sel },

    -- Diff / git
    DiffAdd    = { fg = p.green, bg = p.bg_alt },
    DiffChange = { fg = p.yellow, bg = p.bg_alt },
    DiffDelete = { fg = p.red, bg = p.bg_alt },
    DiffText   = { fg = p.bg, bg = p.yellow },
    Added      = { fg = p.green },
    Changed    = { fg = p.yellow },
    Removed    = { fg = p.red },
  }
end
