-- Hand-authored highlight map. Input: a palette variant table from palette.lua.
-- Adapted for Wana from the coverage of catppuccin & tokyonight, mapped onto
-- Wana's restrained (gruvbox-family) palette. Only palette roles from
-- palette.lua may be referenced (see test_nvim_highlights_use_known_roles).
return function(p)
  return {
    -- Editor UI --------------------------------------------------------------
    Normal        = { fg = p.fg, bg = p.bg },
    NormalNC      = { fg = p.fg, bg = p.bg },
    NormalFloat   = { fg = p.fg, bg = p.bg_alt },
    FloatBorder   = { fg = p.muted, bg = p.bg_alt },
    FloatTitle    = { fg = p.green, bg = p.bg_alt, bold = true },
    FloatFooter   = { fg = p.muted, bg = p.bg_alt },
    Cursor        = { fg = p.bg, bg = p.green },
    lCursor       = { fg = p.bg, bg = p.green },
    CursorIM      = { fg = p.bg, bg = p.green },
    TermCursor    = { fg = p.bg, bg = p.green },
    CursorLine    = { bg = p.bg_alt },
    CursorColumn  = { bg = p.bg_alt },
    CursorLineNr  = { fg = p.yellow, bold = true },
    CursorLineSign = { bg = p.bg },
    CursorLineFold = { bg = p.bg },
    LineNr        = { fg = p.muted },
    LineNrAbove   = { fg = p.muted },
    LineNrBelow   = { fg = p.muted },
    SignColumn    = { bg = p.bg },
    FoldColumn    = { fg = p.muted, bg = p.bg },
    Folded        = { fg = p.muted, bg = p.bg_alt },
    ColorColumn   = { bg = p.bg_alt },
    Visual        = { bg = p.sel },
    VisualNOS     = { bg = p.sel },
    Search        = { fg = p.bg, bg = p.yellow },
    IncSearch     = { fg = p.bg, bg = p.orange },
    CurSearch     = { fg = p.bg, bg = p.orange },
    Substitute    = { fg = p.bg, bg = p.red },
    MatchParen    = { fg = p.cyan, bold = true },
    Pmenu         = { fg = p.fg, bg = p.bg_alt },
    PmenuSel      = { fg = p.bg, bg = p.blue, bold = true },
    PmenuKind     = { fg = p.cyan, bg = p.bg_alt },
    PmenuKindSel  = { fg = p.bg, bg = p.blue },
    PmenuExtra    = { fg = p.muted, bg = p.bg_alt },
    PmenuExtraSel = { fg = p.bg, bg = p.blue },
    PmenuSbar     = { bg = p.surface },
    PmenuThumb    = { bg = p.muted },
    WildMenu      = { fg = p.bg, bg = p.blue },
    StatusLine    = { fg = p.fg, bg = p.surface },
    StatusLineNC  = { fg = p.muted, bg = p.bg_alt },
    TabLine       = { fg = p.muted, bg = p.bg_alt },
    TabLineFill   = { bg = p.bg_dim },
    TabLineSel    = { fg = p.bg, bg = p.blue, bold = true },
    WinBar        = { fg = p.fg, bg = p.bg },
    WinBarNC      = { fg = p.muted, bg = p.bg },
    WinSeparator  = { fg = p.surface },
    VertSplit     = { fg = p.surface },
    NonText       = { fg = p.surface },
    EndOfBuffer   = { fg = p.bg },
    Whitespace    = { fg = p.surface },
    SpecialKey    = { fg = p.muted },
    Conceal       = { fg = p.muted },
    Directory     = { fg = p.blue },
    Title         = { fg = p.green, bold = true },
    QuickFixLine  = { bg = p.sel, bold = true },
    MsgArea       = { fg = p.fg },
    MsgSeparator  = { fg = p.surface },
    ModeMsg       = { fg = p.fg, bold = true },
    MoreMsg       = { fg = p.green },
    Question      = { fg = p.green },
    ErrorMsg      = { fg = p.red },
    WarningMsg    = { fg = p.orange },
    SpellBad      = { undercurl = true, sp = p.red },
    SpellCap      = { undercurl = true, sp = p.yellow },
    SpellLocal    = { undercurl = true, sp = p.cyan },
    SpellRare     = { undercurl = true, sp = p.magenta },
    debugPC       = { bg = p.bg_alt },
    debugBreakpoint = { fg = p.red },
    Winborder     = { fg = p.muted, bg = p.bg_alt },

    -- Legacy syntax ----------------------------------------------------------
    Comment       = { fg = p.muted, italic = true },
    SpecialComment = { fg = p.muted, italic = true },
    Constant      = { fg = p.orange },
    String        = { fg = p.green },
    Character     = { fg = p.green },
    Number        = { fg = p.orange },
    Float         = { fg = p.orange },
    Boolean       = { fg = p.orange },
    Identifier    = { fg = p.fg },
    Function      = { fg = p.blue },
    Statement     = { fg = p.magenta },
    Keyword       = { fg = p.magenta },
    Conditional   = { fg = p.magenta },
    Repeat        = { fg = p.magenta },
    Label         = { fg = p.magenta },
    Exception     = { fg = p.magenta },
    Operator      = { fg = p.cyan },
    PreProc       = { fg = p.cyan },
    Include       = { fg = p.cyan },
    Define        = { fg = p.cyan },
    Macro         = { fg = p.cyan },
    PreCondit     = { fg = p.cyan },
    Type          = { fg = p.yellow },
    StorageClass  = { fg = p.yellow },
    Structure     = { fg = p.yellow },
    Typedef       = { fg = p.yellow },
    Special       = { fg = p.cyan },
    SpecialChar   = { fg = p.brown },
    Tag           = { fg = p.red },
    Delimiter     = { fg = p.fg_dim },
    Debug         = { fg = p.orange },
    Underlined    = { fg = p.blue, underline = true },
    Bold          = { bold = true },
    Italic        = { italic = true },
    Ignore        = { fg = p.muted },
    Todo          = { fg = p.bg, bg = p.yellow, bold = true },
    Error         = { fg = p.red },

    -- Treesitter (modern captures, nvim >= 0.10) -----------------------------
    ["@variable"]               = { fg = p.fg },
    ["@variable.builtin"]       = { fg = p.red, italic = true },
    ["@variable.parameter"]     = { fg = p.fg, italic = true },
    ["@variable.parameter.builtin"] = { fg = p.red, italic = true },
    ["@variable.member"]        = { fg = p.fg },

    ["@constant"]               = { fg = p.orange },
    ["@constant.builtin"]       = { fg = p.orange },
    ["@constant.macro"]         = { fg = p.cyan },

    ["@module"]                 = { fg = p.yellow },
    ["@module.builtin"]         = { fg = p.yellow, italic = true },
    ["@label"]                  = { fg = p.magenta },

    ["@string"]                 = { fg = p.green },
    ["@string.documentation"]   = { fg = p.green, italic = true },
    ["@string.regexp"]          = { fg = p.brown },
    ["@string.escape"]          = { fg = p.cyan },
    ["@string.special"]         = { fg = p.cyan },
    ["@string.special.symbol"]  = { fg = p.orange },
    ["@string.special.url"]     = { fg = p.blue, underline = true },
    ["@string.special.path"]    = { fg = p.green },

    ["@character"]              = { fg = p.green },
    ["@character.special"]      = { fg = p.brown },

    ["@boolean"]               = { fg = p.orange },
    ["@number"]                = { fg = p.orange },
    ["@number.float"]          = { fg = p.orange },

    ["@type"]                  = { fg = p.yellow },
    ["@type.builtin"]          = { fg = p.yellow, italic = true },
    ["@type.definition"]       = { fg = p.yellow },
    ["@type.qualifier"]        = { fg = p.magenta },

    ["@attribute"]             = { fg = p.cyan },
    ["@attribute.builtin"]     = { fg = p.cyan },
    ["@property"]              = { fg = p.fg },

    ["@function"]              = { fg = p.blue },
    ["@function.builtin"]      = { fg = p.cyan },
    ["@function.call"]         = { fg = p.blue },
    ["@function.macro"]        = { fg = p.cyan },
    ["@function.method"]       = { fg = p.blue },
    ["@function.method.call"]  = { fg = p.blue },
    ["@constructor"]           = { fg = p.yellow },

    ["@operator"]              = { fg = p.cyan },

    ["@keyword"]                     = { fg = p.magenta },
    ["@keyword.coroutine"]           = { fg = p.magenta },
    ["@keyword.function"]            = { fg = p.magenta },
    ["@keyword.operator"]            = { fg = p.magenta },
    ["@keyword.import"]              = { fg = p.cyan },
    ["@keyword.type"]                = { fg = p.magenta },
    ["@keyword.modifier"]            = { fg = p.magenta },
    ["@keyword.repeat"]              = { fg = p.magenta },
    ["@keyword.return"]              = { fg = p.magenta },
    ["@keyword.debug"]               = { fg = p.red },
    ["@keyword.exception"]           = { fg = p.magenta },
    ["@keyword.conditional"]         = { fg = p.magenta },
    ["@keyword.conditional.ternary"] = { fg = p.cyan },
    ["@keyword.directive"]           = { fg = p.cyan },
    ["@keyword.directive.define"]    = { fg = p.cyan },

    ["@punctuation.delimiter"] = { fg = p.fg_dim },
    ["@punctuation.bracket"]   = { fg = p.fg_dim },
    ["@punctuation.special"]   = { fg = p.cyan },

    ["@comment"]               = { fg = p.muted, italic = true },
    ["@comment.documentation"] = { fg = p.muted, italic = true },
    ["@comment.error"]         = { fg = p.bg, bg = p.red, bold = true },
    ["@comment.warning"]       = { fg = p.bg, bg = p.orange, bold = true },
    ["@comment.todo"]          = { fg = p.bg, bg = p.yellow, bold = true },
    ["@comment.note"]          = { fg = p.bg, bg = p.cyan, bold = true },

    -- Markup (markdown, help, etc.)
    ["@markup.strong"]         = { bold = true },
    ["@markup.italic"]         = { italic = true },
    ["@markup.strikethrough"]  = { strikethrough = true },
    ["@markup.underline"]      = { underline = true },
    ["@markup.heading"]        = { fg = p.green, bold = true },
    ["@markup.heading.1"]      = { fg = p.green, bold = true },
    ["@markup.heading.2"]      = { fg = p.yellow, bold = true },
    ["@markup.heading.3"]      = { fg = p.orange, bold = true },
    ["@markup.heading.4"]      = { fg = p.blue, bold = true },
    ["@markup.heading.5"]      = { fg = p.magenta, bold = true },
    ["@markup.heading.6"]      = { fg = p.cyan, bold = true },
    ["@markup.quote"]          = { fg = p.muted, italic = true },
    ["@markup.math"]           = { fg = p.orange },
    ["@markup.link"]           = { fg = p.blue },
    ["@markup.link.label"]     = { fg = p.cyan },
    ["@markup.link.url"]       = { fg = p.muted, underline = true },
    ["@markup.raw"]            = { fg = p.green },
    ["@markup.raw.block"]      = { fg = p.fg },
    ["@markup.list"]           = { fg = p.cyan },
    ["@markup.list.checked"]   = { fg = p.green },
    ["@markup.list.unchecked"] = { fg = p.muted },

    ["@diff.plus"]             = { fg = p.green },
    ["@diff.minus"]            = { fg = p.red },
    ["@diff.delta"]            = { fg = p.yellow },

    ["@tag"]                   = { fg = p.red },
    ["@tag.builtin"]           = { fg = p.red },
    ["@tag.attribute"]         = { fg = p.yellow },
    ["@tag.delimiter"]         = { fg = p.fg_dim },

    -- LSP semantic tokens ----------------------------------------------------
    ["@lsp.type.class"]         = { link = "@type" },
    ["@lsp.type.comment"]       = {},
    ["@lsp.type.decorator"]     = { link = "@attribute" },
    ["@lsp.type.enum"]          = { link = "@type" },
    ["@lsp.type.enumMember"]    = { link = "@constant" },
    ["@lsp.type.interface"]     = { link = "@type" },
    ["@lsp.type.function"]      = { link = "@function" },
    ["@lsp.type.macro"]         = { link = "@constant.macro" },
    ["@lsp.type.method"]        = { link = "@function.method" },
    ["@lsp.type.namespace"]     = { link = "@module" },
    ["@lsp.type.parameter"]     = { link = "@variable.parameter" },
    ["@lsp.type.property"]      = { link = "@property" },
    ["@lsp.type.struct"]        = { link = "@type" },
    ["@lsp.type.type"]          = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"]      = {}, -- let treesitter decide plain variables
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.variable.readonly"]       = { link = "@constant" },
    ["@lsp.typemod.keyword.documentation"]   = { link = "@keyword" },

    -- Diagnostics ------------------------------------------------------------
    DiagnosticError = { fg = p.red },
    DiagnosticWarn  = { fg = p.orange },
    DiagnosticInfo  = { fg = p.blue },
    DiagnosticHint  = { fg = p.cyan },
    DiagnosticOk    = { fg = p.green },
    DiagnosticVirtualTextError = { fg = p.red, bg = p.bg_alt },
    DiagnosticVirtualTextWarn  = { fg = p.orange, bg = p.bg_alt },
    DiagnosticVirtualTextInfo  = { fg = p.blue, bg = p.bg_alt },
    DiagnosticVirtualTextHint  = { fg = p.cyan, bg = p.bg_alt },
    DiagnosticVirtualTextOk    = { fg = p.green, bg = p.bg_alt },
    DiagnosticUnderlineError = { undercurl = true, sp = p.red },
    DiagnosticUnderlineWarn  = { undercurl = true, sp = p.orange },
    DiagnosticUnderlineInfo  = { undercurl = true, sp = p.blue },
    DiagnosticUnderlineHint  = { undercurl = true, sp = p.cyan },
    DiagnosticUnderlineOk    = { undercurl = true, sp = p.green },
    DiagnosticFloatingError = { fg = p.red },
    DiagnosticFloatingWarn  = { fg = p.orange },
    DiagnosticFloatingInfo  = { fg = p.blue },
    DiagnosticFloatingHint  = { fg = p.cyan },
    DiagnosticSignError = { fg = p.red },
    DiagnosticSignWarn  = { fg = p.orange },
    DiagnosticSignInfo  = { fg = p.blue },
    DiagnosticSignHint  = { fg = p.cyan },
    DiagnosticDeprecated  = { strikethrough = true, sp = p.muted },
    DiagnosticUnnecessary = { fg = p.muted, italic = true },

    LspReferenceText     = { bg = p.sel },
    LspReferenceRead     = { bg = p.sel },
    LspReferenceWrite    = { bg = p.sel, underline = true },
    LspSignatureActiveParameter = { fg = p.orange, bold = true },
    LspInlayHint         = { fg = p.muted, bg = p.bg_alt, italic = true },
    LspCodeLens          = { fg = p.muted, italic = true },
    LspInfoBorder        = { fg = p.muted, bg = p.bg_alt },

    -- Diff / git -------------------------------------------------------------
    DiffAdd    = { fg = p.green, bg = p.bg_alt },
    DiffChange = { fg = p.yellow, bg = p.bg_alt },
    DiffDelete = { fg = p.red, bg = p.bg_alt },
    DiffText   = { fg = p.bg, bg = p.yellow },
    diffAdded     = { fg = p.green },
    diffRemoved   = { fg = p.red },
    diffChanged   = { fg = p.yellow },
    diffOldFile   = { fg = p.red },
    diffNewFile   = { fg = p.green },
    diffFile      = { fg = p.blue },
    diffLine      = { fg = p.muted },
    diffIndexLine = { fg = p.magenta },
    Added      = { fg = p.green },
    Changed    = { fg = p.yellow },
    Removed    = { fg = p.red },

    -- gitsigns ---------------------------------------------------------------
    GitSignsAdd    = { fg = p.green },
    GitSignsChange = { fg = p.yellow },
    GitSignsDelete = { fg = p.red },
    GitSignsAddNr    = { fg = p.green },
    GitSignsChangeNr = { fg = p.yellow },
    GitSignsDeleteNr = { fg = p.red },
    GitSignsAddLn    = { bg = p.bg_alt },
    GitSignsChangeLn = { bg = p.bg_alt },
    GitSignsDeleteLn = { bg = p.bg_alt },
    GitSignsCurrentLineBlame = { fg = p.muted, italic = true },
    GitSignsAddInline    = { fg = p.bg, bg = p.green },
    GitSignsChangeInline = { fg = p.bg, bg = p.yellow },
    GitSignsDeleteInline = { fg = p.bg, bg = p.red },

    -- telescope --------------------------------------------------------------
    TelescopeNormal        = { fg = p.fg, bg = p.bg_alt },
    TelescopeBorder        = { fg = p.bg_alt, bg = p.bg_alt },
    TelescopeTitle         = { fg = p.fg, bold = true },
    TelescopePromptNormal  = { fg = p.fg, bg = p.surface },
    TelescopePromptBorder  = { fg = p.surface, bg = p.surface },
    TelescopePromptTitle   = { fg = p.bg, bg = p.green, bold = true },
    TelescopePromptPrefix  = { fg = p.green },
    TelescopePromptCounter = { fg = p.muted },
    TelescopeResultsNormal = { fg = p.fg, bg = p.bg_alt },
    TelescopeResultsBorder = { fg = p.bg_alt, bg = p.bg_alt },
    TelescopeResultsTitle  = { fg = p.bg_alt, bg = p.bg_alt },
    TelescopeResultsComment = { fg = p.muted },
    TelescopePreviewNormal = { fg = p.fg, bg = p.bg_dim },
    TelescopePreviewBorder = { fg = p.bg_dim, bg = p.bg_dim },
    TelescopePreviewTitle  = { fg = p.bg, bg = p.blue, bold = true },
    TelescopeSelection     = { bg = p.sel },
    TelescopeSelectionCaret = { fg = p.green, bg = p.sel },
    TelescopeMatching      = { fg = p.yellow, bold = true },
    TelescopeMultiSelection = { fg = p.orange },
    TelescopeMultiIcon     = { fg = p.orange },

    -- nvim-cmp ---------------------------------------------------------------
    CmpItemAbbr           = { fg = p.fg },
    CmpItemAbbrDeprecated = { fg = p.muted, strikethrough = true },
    CmpItemAbbrMatch      = { fg = p.blue, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = p.blue, bold = true },
    CmpItemMenu           = { fg = p.muted, italic = true },
    CmpItemKind           = { fg = p.cyan },
    CmpItemKindText       = { fg = p.fg },
    CmpItemKindVariable   = { fg = p.fg },
    CmpItemKindFunction   = { fg = p.blue },
    CmpItemKindMethod     = { fg = p.blue },
    CmpItemKindConstructor = { fg = p.yellow },
    CmpItemKindClass      = { fg = p.yellow },
    CmpItemKindInterface  = { fg = p.yellow },
    CmpItemKindStruct     = { fg = p.yellow },
    CmpItemKindKeyword    = { fg = p.magenta },
    CmpItemKindProperty   = { fg = p.fg },
    CmpItemKindField      = { fg = p.fg },
    CmpItemKindValue      = { fg = p.orange },
    CmpItemKindConstant   = { fg = p.orange },
    CmpItemKindEnum       = { fg = p.yellow },
    CmpItemKindEnumMember = { fg = p.orange },
    CmpItemKindSnippet    = { fg = p.green },
    CmpItemKindFile       = { fg = p.blue },
    CmpItemKindFolder     = { fg = p.blue },
    CmpItemKindModule     = { fg = p.yellow },
    CmpItemKindColor      = { fg = p.orange },
    CmpItemKindUnit       = { fg = p.orange },
    CmpItemKindReference  = { fg = p.fg },
    CmpItemKindEvent      = { fg = p.yellow },
    CmpItemKindOperator   = { fg = p.cyan },
    CmpItemKindTypeParameter = { fg = p.yellow },

    -- blink.cmp --------------------------------------------------------------
    BlinkCmpMenu           = { fg = p.fg, bg = p.bg_alt },
    BlinkCmpMenuBorder     = { fg = p.muted, bg = p.bg_alt },
    BlinkCmpMenuSelection  = { bg = p.sel },
    BlinkCmpScrollBarThumb = { bg = p.muted },
    BlinkCmpScrollBarGutter = { bg = p.bg_alt },
    BlinkCmpLabel          = { fg = p.fg },
    BlinkCmpLabelDeprecated = { fg = p.muted, strikethrough = true },
    BlinkCmpLabelMatch     = { fg = p.blue, bold = true },
    BlinkCmpLabelDetail    = { fg = p.muted },
    BlinkCmpLabelDescription = { fg = p.muted, italic = true },
    BlinkCmpKind           = { fg = p.cyan },
    BlinkCmpSource         = { fg = p.muted },
    BlinkCmpGhostText      = { fg = p.muted, italic = true },
    BlinkCmpDoc            = { fg = p.fg, bg = p.bg_alt },
    BlinkCmpDocBorder      = { fg = p.muted, bg = p.bg_alt },
    BlinkCmpSignatureHelp  = { fg = p.fg, bg = p.bg_alt },
    BlinkCmpSignatureHelpBorder = { fg = p.muted, bg = p.bg_alt },
    BlinkCmpSignatureHelpActiveParameter = { fg = p.orange, bold = true },

    -- nvim-tree --------------------------------------------------------------
    NvimTreeNormal        = { fg = p.fg, bg = p.bg_dim },
    NvimTreeNormalNC      = { fg = p.fg, bg = p.bg_dim },
    NvimTreeEndOfBuffer   = { fg = p.bg_dim },
    NvimTreeRootFolder    = { fg = p.magenta, bold = true },
    NvimTreeFolderName    = { fg = p.blue },
    NvimTreeFolderIcon    = { fg = p.blue },
    NvimTreeOpenedFolderName = { fg = p.blue, bold = true },
    NvimTreeEmptyFolderName  = { fg = p.muted },
    NvimTreeSymlink       = { fg = p.cyan },
    NvimTreeSpecialFile   = { fg = p.yellow, underline = true },
    NvimTreeImageFile     = { fg = p.magenta },
    NvimTreeExecFile      = { fg = p.green },
    NvimTreeIndentMarker  = { fg = p.surface },
    NvimTreeWindowPicker  = { fg = p.bg, bg = p.orange, bold = true },
    NvimTreeGitDirtyIcon   = { fg = p.yellow },
    NvimTreeGitStagedIcon  = { fg = p.green },
    NvimTreeGitMergeIcon   = { fg = p.orange },
    NvimTreeGitRenamedIcon = { fg = p.magenta },
    NvimTreeGitNewIcon     = { fg = p.green },
    NvimTreeGitDeletedIcon = { fg = p.red },
    NvimTreeGitIgnoredIcon = { fg = p.muted },
    NvimTreeGitFileDirtyHL   = { fg = p.yellow },
    NvimTreeGitFileStagedHL  = { fg = p.green },
    NvimTreeGitFileMergeHL   = { fg = p.orange },
    NvimTreeGitFileRenamedHL = { fg = p.magenta },
    NvimTreeGitFileNewHL     = { fg = p.green },
    NvimTreeGitFileDeletedHL = { fg = p.red },
    NvimTreeGitFileIgnoredHL = { fg = p.muted },

    -- neo-tree ---------------------------------------------------------------
    NeoTreeNormal         = { fg = p.fg, bg = p.bg_dim },
    NeoTreeNormalNC       = { fg = p.fg, bg = p.bg_dim },
    NeoTreeEndOfBuffer    = { fg = p.bg_dim },
    NeoTreeDirectoryName  = { fg = p.blue },
    NeoTreeDirectoryIcon  = { fg = p.blue },
    NeoTreeRootName       = { fg = p.magenta, bold = true },
    NeoTreeFileName       = { fg = p.fg },
    NeoTreeFileIcon       = { fg = p.cyan },
    NeoTreeIndentMarker   = { fg = p.surface },
    NeoTreeExpander       = { fg = p.muted },
    NeoTreeDimText        = { fg = p.muted },
    NeoTreeGitAdded       = { fg = p.green },
    NeoTreeGitModified    = { fg = p.yellow },
    NeoTreeGitDeleted     = { fg = p.red },
    NeoTreeGitRenamed     = { fg = p.magenta },
    NeoTreeGitUntracked   = { fg = p.green },
    NeoTreeGitStaged      = { fg = p.green },
    NeoTreeGitUnstaged    = { fg = p.yellow },
    NeoTreeGitIgnored     = { fg = p.muted },
    NeoTreeGitConflict    = { fg = p.orange },
    NeoTreeModified       = { fg = p.yellow },
    NeoTreeFloatBorder    = { fg = p.muted, bg = p.bg_alt },
    NeoTreeFloatTitle     = { fg = p.green, bg = p.bg_alt, bold = true },
    NeoTreeTabActive      = { fg = p.fg, bg = p.bg_dim, bold = true },
    NeoTreeTabInactive    = { fg = p.muted, bg = p.bg },
    NeoTreeTabSeparatorActive   = { fg = p.bg_dim, bg = p.bg_dim },
    NeoTreeTabSeparatorInactive = { fg = p.bg, bg = p.bg },

    -- which-key --------------------------------------------------------------
    WhichKey          = { fg = p.magenta },
    WhichKeyGroup     = { fg = p.blue },
    WhichKeyDesc      = { fg = p.fg },
    WhichKeySeparator = { fg = p.muted },
    WhichKeyNormal    = { bg = p.bg_alt },
    WhichKeyBorder    = { fg = p.muted, bg = p.bg_alt },
    WhichKeyValue     = { fg = p.muted },
    WhichKeyIcon      = { fg = p.cyan },
    WhichKeyTitle     = { fg = p.green, bold = true },

    -- indent-blankline (ibl v3) ----------------------------------------------
    IblIndent    = { fg = p.surface },
    IblWhitespace = { fg = p.surface },
    IblScope     = { fg = p.muted },

    -- bufferline -------------------------------------------------------------
    BufferLineFill              = { bg = p.bg_dim },
    BufferLineBackground        = { fg = p.muted, bg = p.bg_dim },
    BufferLineBufferVisible     = { fg = p.muted, bg = p.bg_dim },
    BufferLineBufferSelected    = { fg = p.fg, bg = p.bg, bold = true },
    BufferLineTabSelected       = { fg = p.green, bg = p.bg },
    BufferLineSeparator         = { fg = p.bg_dim, bg = p.bg_dim },
    BufferLineSeparatorVisible  = { fg = p.bg_dim, bg = p.bg_dim },
    BufferLineSeparatorSelected = { fg = p.bg_dim, bg = p.bg },
    BufferLineIndicatorSelected = { fg = p.green, bg = p.bg },
    BufferLineModified          = { fg = p.yellow, bg = p.bg_dim },
    BufferLineModifiedVisible   = { fg = p.yellow, bg = p.bg_dim },
    BufferLineModifiedSelected  = { fg = p.yellow, bg = p.bg },
    BufferLineCloseButton       = { fg = p.muted, bg = p.bg_dim },
    BufferLineCloseButtonSelected = { fg = p.red, bg = p.bg },
    BufferLineError             = { fg = p.red, bg = p.bg_dim },
    BufferLineWarning           = { fg = p.orange, bg = p.bg_dim },

    -- nvim-notify ------------------------------------------------------------
    NotifyERRORBorder = { fg = p.red },
    NotifyWARNBorder  = { fg = p.orange },
    NotifyINFOBorder  = { fg = p.blue },
    NotifyDEBUGBorder = { fg = p.muted },
    NotifyTRACEBorder = { fg = p.magenta },
    NotifyERRORIcon   = { fg = p.red },
    NotifyWARNIcon    = { fg = p.orange },
    NotifyINFOIcon    = { fg = p.blue },
    NotifyDEBUGIcon   = { fg = p.muted },
    NotifyTRACEIcon   = { fg = p.magenta },
    NotifyERRORTitle  = { fg = p.red, bold = true },
    NotifyWARNTitle   = { fg = p.orange, bold = true },
    NotifyINFOTitle   = { fg = p.blue, bold = true },
    NotifyDEBUGTitle  = { fg = p.muted, bold = true },
    NotifyTRACETitle  = { fg = p.magenta, bold = true },
    NotifyBackground  = { bg = p.bg_alt },

    -- noice ------------------------------------------------------------------
    NoiceCmdline            = { fg = p.fg, bg = p.bg_alt },
    NoiceCmdlinePopup       = { fg = p.fg, bg = p.bg_alt },
    NoiceCmdlinePopupBorder = { fg = p.muted, bg = p.bg_alt },
    NoiceCmdlineIcon        = { fg = p.green },
    NoiceConfirm            = { fg = p.fg, bg = p.bg_alt },
    NoiceConfirmBorder      = { fg = p.muted, bg = p.bg_alt },
    NoiceMini               = { fg = p.fg, bg = p.bg_alt },
    NoicePopupmenu          = { fg = p.fg, bg = p.bg_alt },
    NoicePopupmenuSelected  = { fg = p.bg, bg = p.blue, bold = true },
    NoicePopupmenuMatch     = { fg = p.yellow, bold = true },
    NoiceVirtualText        = { fg = p.muted },

    -- trouble ----------------------------------------------------------------
    TroubleNormal   = { fg = p.fg, bg = p.bg_dim },
    TroubleNormalNC = { fg = p.fg, bg = p.bg_dim },
    TroubleText     = { fg = p.fg },
    TroubleCount    = { fg = p.magenta, bold = true },
    TroubleIndent   = { fg = p.surface },
    TroubleIndentFoldOpen   = { fg = p.muted },
    TroubleIndentFoldClosed = { fg = p.muted },
    TroubleFilename = { fg = p.blue },
    TroublePos      = { fg = p.yellow },
    TroubleSource   = { fg = p.muted, italic = true },

    -- flash.nvim -------------------------------------------------------------
    FlashBackdrop = { fg = p.muted },
    FlashMatch    = { fg = p.bg, bg = p.cyan },
    FlashCurrent  = { fg = p.bg, bg = p.orange },
    FlashLabel    = { fg = p.bg, bg = p.magenta, bold = true },
    FlashPrompt   = { fg = p.fg, bg = p.bg_alt },

    -- leap.nvim / hop.nvim ---------------------------------------------------
    LeapMatch    = { fg = p.bg, bg = p.magenta, bold = true },
    LeapLabel    = { fg = p.bg, bg = p.orange, bold = true },
    LeapBackdrop = { fg = p.muted },
    HopNextKey   = { fg = p.magenta, bold = true },
    HopNextKey1  = { fg = p.blue, bold = true },
    HopNextKey2  = { fg = p.cyan },
    HopUnmatched = { fg = p.muted },

    -- lazy.nvim UI -----------------------------------------------------------
    LazyNormal        = { fg = p.fg, bg = p.bg_alt },
    LazyButton        = { fg = p.fg, bg = p.surface },
    LazyButtonActive  = { fg = p.bg, bg = p.green, bold = true },
    LazyH1            = { fg = p.bg, bg = p.green, bold = true },
    LazyH2            = { fg = p.green, bold = true },
    LazySpecial       = { fg = p.cyan },
    LazyComment       = { fg = p.muted, italic = true },
    LazyProp          = { fg = p.fg_dim },
    LazyReasonPlugin  = { fg = p.magenta },
    LazyReasonEvent   = { fg = p.yellow },
    LazyReasonCmd     = { fg = p.blue },
    LazyReasonFt      = { fg = p.cyan },
    LazyReasonKeys    = { fg = p.orange },
    LazyReasonStart   = { fg = p.green },
    LazyReasonSource  = { fg = p.brown },
    LazyProgressDone  = { fg = p.green },
    LazyProgressTodo  = { fg = p.surface },

    -- mason ------------------------------------------------------------------
    MasonNormal          = { fg = p.fg, bg = p.bg_alt },
    MasonHeader          = { fg = p.bg, bg = p.green, bold = true },
    MasonHeaderSecondary = { fg = p.bg, bg = p.blue, bold = true },
    MasonHighlight       = { fg = p.green },
    MasonHighlightBlock  = { fg = p.bg, bg = p.green },
    MasonHighlightBlockBold = { fg = p.bg, bg = p.green, bold = true },
    MasonMuted           = { fg = p.muted },
    MasonMutedBlock      = { fg = p.fg, bg = p.surface },
    MasonError           = { fg = p.red },

    -- nvim-dap / dap-ui ------------------------------------------------------
    DapBreakpoint         = { fg = p.red },
    DapBreakpointCondition = { fg = p.orange },
    DapBreakpointRejected = { fg = p.muted },
    DapLogPoint           = { fg = p.blue },
    DapStopped            = { fg = p.green },
    DapStoppedLine        = { bg = p.bg_alt },
    DapUIVariable         = { fg = p.fg },
    DapUIValue            = { fg = p.cyan },
    DapUIType             = { fg = p.yellow },
    DapUIModifiedValue    = { fg = p.orange, bold = true },
    DapUIDecoration       = { fg = p.blue },
    DapUIThread           = { fg = p.green },
    DapUIStoppedThread    = { fg = p.blue },
    DapUISource           = { fg = p.magenta },
    DapUILineNumber       = { fg = p.muted },
    DapUIFloatBorder      = { fg = p.muted },
    DapUIWatchesEmpty     = { fg = p.muted },
    DapUIWatchesValue     = { fg = p.green },
    DapUIWatchesError     = { fg = p.red },
    DapUIBreakpointsPath  = { fg = p.blue },
    DapUIBreakpointsInfo  = { fg = p.green },
    DapUIBreakpointsCurrentLine = { fg = p.green, bold = true },
    DapUIScope            = { fg = p.cyan },

    -- treesitter-context -----------------------------------------------------
    TreesitterContext           = { bg = p.bg_alt },
    TreesitterContextLineNumber = { fg = p.muted, bg = p.bg_alt },
    TreesitterContextBottom     = { underline = true, sp = p.surface },

    -- vim-illuminate ---------------------------------------------------------
    IlluminatedWordText  = { bg = p.sel },
    IlluminatedWordRead  = { bg = p.sel },
    IlluminatedWordWrite = { bg = p.sel, underline = true },

    -- rainbow-delimiters -----------------------------------------------------
    RainbowDelimiterRed    = { fg = p.red },
    RainbowDelimiterYellow = { fg = p.yellow },
    RainbowDelimiterBlue   = { fg = p.blue },
    RainbowDelimiterOrange = { fg = p.orange },
    RainbowDelimiterGreen  = { fg = p.green },
    RainbowDelimiterViolet = { fg = p.magenta },
    RainbowDelimiterCyan   = { fg = p.cyan },

    -- render-markdown --------------------------------------------------------
    RenderMarkdownH1     = { fg = p.green, bold = true },
    RenderMarkdownH2     = { fg = p.yellow, bold = true },
    RenderMarkdownH3     = { fg = p.orange, bold = true },
    RenderMarkdownH4     = { fg = p.blue, bold = true },
    RenderMarkdownH5     = { fg = p.magenta, bold = true },
    RenderMarkdownH6     = { fg = p.cyan, bold = true },
    RenderMarkdownH1Bg   = { fg = p.green, bg = p.bg_alt },
    RenderMarkdownH2Bg   = { fg = p.yellow, bg = p.bg_alt },
    RenderMarkdownH3Bg   = { fg = p.orange, bg = p.bg_alt },
    RenderMarkdownH4Bg   = { fg = p.blue, bg = p.bg_alt },
    RenderMarkdownH5Bg   = { fg = p.magenta, bg = p.bg_alt },
    RenderMarkdownH6Bg   = { fg = p.cyan, bg = p.bg_alt },
    RenderMarkdownCode   = { bg = p.bg_alt },
    RenderMarkdownCodeInline = { fg = p.green, bg = p.bg_alt },
    RenderMarkdownBullet = { fg = p.cyan },
    RenderMarkdownQuote  = { fg = p.muted },
    RenderMarkdownDash   = { fg = p.surface },
    RenderMarkdownLink   = { fg = p.blue, underline = true },
    RenderMarkdownTableHead = { fg = p.muted },
    RenderMarkdownTableRow  = { fg = p.fg_dim },

    -- headlines.nvim ---------------------------------------------------------
    Headline  = { bg = p.bg_alt },
    CodeBlock = { bg = p.bg_alt },
    Dash      = { fg = p.surface },
    Quote     = { fg = p.muted },

    -- nvim-navic -------------------------------------------------------------
    NavicText          = { fg = p.fg },
    NavicSeparator     = { fg = p.muted },
    NavicIconsFile          = { fg = p.blue },
    NavicIconsModule        = { fg = p.yellow },
    NavicIconsNamespace     = { fg = p.yellow },
    NavicIconsPackage       = { fg = p.yellow },
    NavicIconsClass         = { fg = p.yellow },
    NavicIconsMethod        = { fg = p.blue },
    NavicIconsProperty      = { fg = p.fg },
    NavicIconsField         = { fg = p.fg },
    NavicIconsConstructor   = { fg = p.yellow },
    NavicIconsEnum          = { fg = p.yellow },
    NavicIconsInterface     = { fg = p.yellow },
    NavicIconsFunction      = { fg = p.blue },
    NavicIconsVariable      = { fg = p.fg },
    NavicIconsConstant      = { fg = p.orange },
    NavicIconsString        = { fg = p.green },
    NavicIconsNumber        = { fg = p.orange },
    NavicIconsBoolean       = { fg = p.orange },
    NavicIconsArray         = { fg = p.fg },
    NavicIconsObject        = { fg = p.fg },
    NavicIconsKey           = { fg = p.magenta },
    NavicIconsNull          = { fg = p.orange },
    NavicIconsEnumMember    = { fg = p.orange },
    NavicIconsStruct        = { fg = p.yellow },
    NavicIconsEvent         = { fg = p.yellow },
    NavicIconsOperator      = { fg = p.cyan },
    NavicIconsTypeParameter = { fg = p.yellow },

    -- mini.nvim (common modules) ---------------------------------------------
    MiniIndentscopeSymbol = { fg = p.muted },
    MiniIndentscopePrefix = { nocombine = true },
    MiniCursorword        = { bg = p.sel },
    MiniCursorwordCurrent = { bg = p.sel },
    MiniTrailspace        = { bg = p.red },
    MiniStatuslineModeNormal  = { fg = p.bg, bg = p.green, bold = true },
    MiniStatuslineModeInsert  = { fg = p.bg, bg = p.blue, bold = true },
    MiniStatuslineModeVisual  = { fg = p.bg, bg = p.magenta, bold = true },
    MiniStatuslineModeReplace = { fg = p.bg, bg = p.red, bold = true },
    MiniStatuslineModeCommand = { fg = p.bg, bg = p.orange, bold = true },
    MiniStatuslineFilename    = { fg = p.fg, bg = p.surface },
    MiniStatuslineInactive    = { fg = p.muted, bg = p.bg_alt },
    MiniDiffSignAdd    = { fg = p.green },
    MiniDiffSignChange = { fg = p.yellow },
    MiniDiffSignDelete = { fg = p.red },
    MiniFilesTitleFocused = { fg = p.green, bold = true },
    MiniPickMatchCurrent  = { bg = p.sel },
    MiniPickMatchMarked   = { fg = p.orange },

    -- snacks.nvim ------------------------------------------------------------
    SnacksNormal    = { fg = p.fg, bg = p.bg_alt },
    SnacksNormalNC  = { fg = p.fg, bg = p.bg_alt },
    SnacksWinBar    = { fg = p.fg, bg = p.bg_alt, bold = true },
    SnacksWinBarNC  = { fg = p.muted, bg = p.bg_alt },
    SnacksBackdrop  = { bg = p.bg_dim },
    -- notifier
    SnacksNotifierInfo        = { fg = p.blue },
    SnacksNotifierIconInfo    = { fg = p.blue },
    SnacksNotifierTitleInfo   = { fg = p.blue, bold = true },
    SnacksNotifierBorderInfo  = { fg = p.blue },
    SnacksNotifierFooterInfo  = { fg = p.muted },
    SnacksNotifierWarn        = { fg = p.orange },
    SnacksNotifierIconWarn    = { fg = p.orange },
    SnacksNotifierTitleWarn   = { fg = p.orange, bold = true },
    SnacksNotifierBorderWarn  = { fg = p.orange },
    SnacksNotifierFooterWarn  = { fg = p.muted },
    SnacksNotifierError       = { fg = p.red },
    SnacksNotifierIconError   = { fg = p.red },
    SnacksNotifierTitleError  = { fg = p.red, bold = true },
    SnacksNotifierBorderError = { fg = p.red },
    SnacksNotifierFooterError = { fg = p.muted },
    SnacksNotifierDebug       = { fg = p.muted },
    SnacksNotifierIconDebug   = { fg = p.muted },
    SnacksNotifierTitleDebug  = { fg = p.muted, bold = true },
    SnacksNotifierBorderDebug = { fg = p.muted },
    SnacksNotifierFooterDebug = { fg = p.muted },
    SnacksNotifierTrace       = { fg = p.magenta },
    SnacksNotifierIconTrace   = { fg = p.magenta },
    SnacksNotifierTitleTrace  = { fg = p.magenta, bold = true },
    SnacksNotifierBorderTrace = { fg = p.magenta },
    SnacksNotifierFooterTrace = { fg = p.muted },
    -- dashboard
    SnacksDashboardNormal   = { fg = p.fg },
    SnacksDashboardDesc     = { fg = p.blue },
    SnacksDashboardFile     = { fg = p.fg },
    SnacksDashboardDir      = { fg = p.muted },
    SnacksDashboardFooter   = { fg = p.muted, italic = true },
    SnacksDashboardHeader   = { fg = p.green, bold = true },
    SnacksDashboardIcon     = { fg = p.cyan },
    SnacksDashboardKey      = { fg = p.orange },
    SnacksDashboardTerminal = { fg = p.fg },
    SnacksDashboardSpecial  = { fg = p.magenta },
    SnacksDashboardTitle    = { fg = p.green, bold = true },
    -- indent
    SnacksIndent      = { fg = p.surface },
    SnacksIndentScope = { fg = p.muted },
    -- picker
    SnacksPicker             = { fg = p.fg, bg = p.bg_alt },
    SnacksPickerBorder       = { fg = p.muted, bg = p.bg_alt },
    SnacksPickerSelected     = { fg = p.orange },
    SnacksPickerMatch        = { fg = p.yellow, bold = true },
    SnacksPickerInput        = { fg = p.fg, bg = p.surface },
    SnacksPickerInputBorder  = { fg = p.surface, bg = p.surface },
    SnacksPickerPrompt       = { fg = p.green },
    SnacksPickerTitle        = { fg = p.bg, bg = p.green, bold = true },
    SnacksPickerPreviewTitle = { fg = p.bg, bg = p.blue, bold = true },
    SnacksPickerInputTitle   = { fg = p.bg, bg = p.orange, bold = true },
    SnacksPickerListTitle    = { fg = p.muted, bg = p.bg_alt },

    -- fzf-lua -----------------------------------------------------------------
    FzfLuaNormal            = { fg = p.fg, bg = p.bg_alt },
    FzfLuaBorder            = { fg = p.muted, bg = p.bg_alt },
    FzfLuaTitle             = { fg = p.bg, bg = p.green, bold = true },
    FzfLuaTitleFlags        = { fg = p.orange },
    FzfLuaBackdrop          = { bg = p.bg_dim },
    FzfLuaPreviewNormal     = { fg = p.fg, bg = p.bg_dim },
    FzfLuaPreviewBorder     = { fg = p.muted, bg = p.bg_dim },
    FzfLuaPreviewTitle      = { fg = p.bg, bg = p.blue, bold = true },
    FzfLuaCursor            = { fg = p.bg, bg = p.fg },
    FzfLuaCursorLine        = { bg = p.sel },
    FzfLuaCursorLineNr      = { fg = p.yellow, bg = p.sel },
    FzfLuaSearch            = { fg = p.yellow, bold = true },
    FzfLuaScrollBorderEmpty = { fg = p.surface },
    FzfLuaScrollBorderFull  = { fg = p.muted },
    FzfLuaScrollFloatEmpty  = { fg = p.surface },
    FzfLuaScrollFloatFull   = { fg = p.muted },
    FzfLuaHelpNormal        = { fg = p.fg, bg = p.bg_alt },
    FzfLuaHelpBorder        = { fg = p.muted, bg = p.bg_alt },
    FzfLuaHeaderBind        = { fg = p.orange },
    FzfLuaHeaderText        = { fg = p.red },
    FzfLuaPathColNr         = { fg = p.cyan },
    FzfLuaPathLineNr        = { fg = p.green },
    FzfLuaBufName           = { fg = p.magenta },
    FzfLuaBufId             = { fg = p.orange },
    FzfLuaBufNr             = { fg = p.orange },
    FzfLuaBufLineNr         = { fg = p.muted },
    FzfLuaBufFlagCur        = { fg = p.red },
    FzfLuaBufFlagAlt        = { fg = p.blue },
    FzfLuaTabTitle          = { fg = p.cyan, bold = true },
    FzfLuaTabMarker         = { fg = p.yellow, bold = true },
    FzfLuaDirIcon           = { fg = p.blue },
    FzfLuaDirPart           = { fg = p.muted },
    FzfLuaFilePart          = { fg = p.fg },
    FzfLuaLivePrompt        = { fg = p.fg },
    FzfLuaLiveSym           = { fg = p.red },
    -- fzf process colors (the fzf binary's own UI)
    FzfLuaFzfNormal         = { fg = p.fg },
    FzfLuaFzfCursorLine     = { bg = p.sel },
    FzfLuaFzfMatch          = { fg = p.yellow, bold = true },
    FzfLuaFzfBorder         = { fg = p.muted },
    FzfLuaFzfScrollbar      = { fg = p.muted },
    FzfLuaFzfSeparator      = { fg = p.surface },
    FzfLuaFzfGutter         = { bg = p.bg_alt },
    FzfLuaFzfHeader         = { fg = p.red },
    FzfLuaFzfInfo           = { fg = p.muted },
    FzfLuaFzfPointer        = { fg = p.green },
    FzfLuaFzfMarker         = { fg = p.orange },
    FzfLuaFzfPrompt         = { fg = p.green },
    FzfLuaFzfQuery          = { fg = p.fg },
    FzfLuaFzfSpinner        = { fg = p.green },

    -- mini.clue ---------------------------------------------------------------
    MiniClueBorder              = { fg = p.muted, bg = p.bg_alt },
    MiniClueTitle               = { fg = p.green, bg = p.bg_alt, bold = true },
    MiniClueDescGroup           = { fg = p.yellow },
    MiniClueDescSingle          = { fg = p.fg },
    MiniClueNextKey             = { fg = p.green, bold = true },
    MiniClueNextKeyWithPostkeys = { fg = p.orange, bold = true },
    MiniClueSeparator           = { fg = p.surface },

    -- blink.indent -----------------------------------------------------------
    BlinkIndent                = { fg = p.surface },
    BlinkIndentBlue            = { fg = p.blue },
    BlinkIndentBlueUnderline   = { fg = p.blue, underline = true },
    BlinkIndentOrange          = { fg = p.orange },
    BlinkIndentOrangeUnderline = { fg = p.orange, underline = true },
    BlinkIndentViolet          = { fg = p.magenta },
    BlinkIndentVioletUnderline = { fg = p.magenta, underline = true },

    -- pathfinder.nvim --------------------------------------------------------
    -- (plugin only applies these if left undefined; defining them replaces its
    --  hardcoded neon defaults)
    PathfinderDim             = { fg = p.muted },
    PathfinderHighlight       = { fg = p.fg_bright },
    PathfinderNumberHighlight = { fg = p.green, bold = true },
    PathfinderColumnHighlight = { fg = p.yellow, bold = true },
    PathfinderNextKey         = { fg = p.magenta, bold = true },
    PathfinderFutureKeys      = { fg = p.br_magenta },
  }
end
